language: c
compiler:
  - gcc
before_install: 
  - sudo apt-get update -q
  - sudo apt-get install -qq autoconf libltdl-dev libpng12-dev libmysqlclient-dev libmysqld-dev bison flex libgd2-xpm-dev
script: ./bootstrap.sh && ./configure && make
